export default {
	/* LOGIN */
	IS_REQUEST_LOGIN: 'IS_REQUEST_LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILED: 'LOGIN_FAILED',
	/* ADD USER */
	ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
	ADD_USER_FAILED: 'ADD_USER_FAILED',
	/* DASHBOARD */
	IS_DASHBOARD_REQUEST: 'IS_DASHBOARD_REQUEST',
	ADD_DAILY_TASK_CATEGORY: 'ADD_DAILY_TASK_CATEGORY',
	ADD_DAILY_TASK_CATEGORY_FAILED: 'ADD_DAILY_TASK_CATEGORY_FAILED',
	GET_DAILY_TASK_CATEGORY: 'GET_DAILY_TASK_CATEGORY',
	GET_DAILY_TASK_CATEGORY_FAILED: 'GET_DAILY_TASK_CATEGORY_FAILED',
	UPDATE_DAILY_TASK_STATUS: 'UPDATE_DAILY_TASK_STATUS',
	UPDATE_DAILY_TASK_STATUS_FAILED: 'UPDATE_DAILY_TASK_STATUS_FAILED',
	UPDATE_DAILY_TASK_REQUEST: 'UPDATE_DAILY_TASK_REQUEST',
	RESET_DASHBOARD_DATA: 'RESET_DASHBOARD_DATA',
	FETCH_TASK_REPORT: 'FETCH_TASK_REPORT',
  GETTING_TASK_REPORT_SUCCESS: 'GETTING_TASK_REPORT_SUCCESS',
	GETTING_TASK_REPORT_FAILED: 'GETTING_TASK_REPORT_FAILED',
	DELETE_TASK_ROW: 'DELETE_TASK_ROW',
  DELETE_TASK_ROW_SUCCESS: 'DELETE_TASK_ROW_SUCCESS',
  DELETE_TASK_ROW_FAILED: 'DELETE_TASK_ROW_FAILED'
};
